2020-12-24 13:22:50,440 DEBUG (MadisServer::post) QueryExecutionException: &2 0 -1 1519351 0 0 0
!(mapi:monetdb://monetdb@88.197.53.136/voc10) Aggregate sys.pearson_global not found
!25005!Current transaction is aborted (please ROLLBACK)

2020-12-24 13:22:50,441 INFO 200 POST / (127.0.0.1) 168.32ms
2020-12-24 13:22:50,441 ERROR Uncaught exception POST / (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:7779', method='POST', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/openaire/.local/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "mserver.py", line 52, in post
    result = await run_algorithm.run(algorithm, params, db_objects)
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/run_algorithm.py", line 38, in run
    result = await scheduler_instance.schedule()
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/scheduler.py", line 52, in schedule
    result = await self.run_global(self.step, task['run_global'])
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/scheduler.py", line 116, in run_global
    result = await self.task_executor.task_global(step, self.global_schema, step_global['sqlscript'])
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/task_executor.py", line 143, in task_global
    result = await cur.execute(query)
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/aiopymonetdb/sql/cursors.py", line 174, in execute
    block = await self.connection.execute(query)
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/aiopymonetdb/sql/connections.py", line 277, in execute
    return await self.command("s" + query + "\n;")
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/aiopymonetdb/sql/connections.py", line 282, in command
    return await self.mapi.cmd(command)
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/aiopymonetdb/mapi_async.py", line 297, in cmd
    raise exception('\n'.join(lines))
pymonetdb.exceptions.OperationalError: &2 0 -1 1519351 0 0 0
!(mapi:monetdb://monetdb@88.197.53.136/voc10) Aggregate sys.pearson_global not found
!25005!Current transaction is aborted (please ROLLBACK)

2020-12-24 13:23:01,482 DEBUG (MadisServer::post) str_result-> [(3.3526948449419853, 3.5521900839009275), (3.0184047361222612, 3.1963818177134553), (3.7195807209950855, 3.942784089111318)]
2020-12-24 13:23:01,483 INFO 200 POST / (127.0.0.1) 4815.33ms
2020-12-24 13:23:08,887 DEBUG (MadisServer::post) str_result-> [(3.3526948449419853, 3.5521900839009275), (3.0184047361222612, 3.1963818177134553), (3.7195807209950855, 3.942784089111318)]
2020-12-24 13:23:08,887 INFO 200 POST / (127.0.0.1) 4828.16ms
2020-12-24 13:23:20,125 DEBUG (MadisServer::post) str_result-> [(3.3526948449419853, 3.5521900839009275), (3.0184047361222612, 3.1963818177134553), (3.7195807209950855, 3.942784089111318)]
2020-12-24 13:23:20,125 INFO 200 POST / (127.0.0.1) 4602.31ms
2020-12-24 13:23:30,009 DEBUG (MadisServer::post) str_result-> [(3.3526948449419853, 3.5521900839009275), (3.0184047361222612, 3.1963818177134553), (3.7195807209950855, 3.942784089111318)]
2020-12-24 13:23:30,009 INFO 200 POST / (127.0.0.1) 4977.99ms
2020-12-24 13:23:34,307 DEBUG (MadisServer::post) str_result-> [(1,)]
2020-12-24 13:23:34,308 INFO 200 POST / (127.0.0.1) 1400.00ms
2020-12-24 13:23:39,615 DEBUG (MadisServer::post) QueryExecutionException: argument of type 'NoneType' is not iterable
2020-12-24 13:23:39,616 INFO 200 POST / (127.0.0.1) 99.02ms
2020-12-24 13:23:39,616 ERROR Uncaught exception POST / (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:7779', method='POST', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/openaire/.local/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "mserver.py", line 52, in post
    result = await run_algorithm.run(algorithm, params, db_objects)
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/run_algorithm.py", line 38, in run
    result = await scheduler_instance.schedule()
  File "/home/openaire/exareme2_runtime/monetdb_federated_poc/global/scheduler.py", line 40, in schedule
    if 'set_schema' in task:
TypeError: argument of type 'NoneType' is not iterable
